name: Build Release Binaries

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }} Binary
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        include:
          - os: ubuntu-20.04
            asset_name: video-analyzer
            asset_content_type: application/x-executable
          - os: windows-latest
            asset_name: video-analyzer.exe
            asset_content_type: application/x-msdownload
          - os: macos-latest
            asset_name: video-analyzer-macos
            asset_content_type: application/x-executable

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    # Create version file for Windows
    - name: Create Version Info
      if: matrix.os == 'windows-latest'
      run: |
        echo "VSVersionInfo(
          ffi=FixedFileInfo(
            filevers=(1, 0, 0, 0),
            prodvers=(1, 0, 0, 0),
            mask=0x3f,
            flags=0x0,
            OS=0x40004,
            fileType=0x1,
            subtype=0x0,
            date=(0, 0)
          ),
          kids=[
            StringFileInfo([
              StringTable(
                u'040904B0',
                [StringStruct(u'CompanyName', u'Video Analyzer Open Source Project'),
                 StringStruct(u'FileDescription', u'Video Analyzer - Find and manage duplicate videos'),
                 StringStruct(u'FileVersion', u'1.0.0'),
                 StringStruct(u'InternalName', u'video_analyzer'),
                 StringStruct(u'LegalCopyright', u'Open Source - MIT License'),
                 StringStruct(u'OriginalFilename', u'video-analyzer.exe'),
                 StringStruct(u'ProductName', u'Video Analyzer'),
                 StringStruct(u'ProductVersion', u'1.0.0')])
            ]),
            VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
          ]
        )" > version_info.txt

    # Generate SHA256 checksums before building
    - name: Create build info
      shell: bash
      run: |
        echo "Build Date: $(date -u)" > build_info.txt
        echo "Commit: ${{ github.sha }}" >> build_info.txt
        echo "Source: https://github.com/${{ github.repository }}" >> build_info.txt

    - name: Build binary
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          python -m PyInstaller --clean --onefile \
            --name=${{ matrix.asset_name }} \
            --add-data="README.md:." \
            --add-data="build_info.txt:." \
            --version-file=version_info.txt \
            --uac-admin \
            --win-private-assemblies \
            --win-no-prefer-redirects \
            --disable-windowed-traceback \
            video_analyzer/__main__.py
        else
          python -m PyInstaller --clean --onefile \
            --name=${{ matrix.asset_name }} \
            --add-data="README.md:." \
            --add-data="build_info.txt:." \
            video_analyzer/__main__.py
        fi
      shell: bash

    # Generate checksums
    - name: Generate SHA256
      run: |
        cd dist
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          certutil -hashfile ${{ matrix.asset_name }} SHA256 > ${{ matrix.asset_name }}.sha256
        else
          shasum -a 256 ${{ matrix.asset_name }} > ${{ matrix.asset_name }}.sha256
        fi
      shell: bash

    # Linux GPG Signing (free)
    - name: Sign Linux Binary
      if: matrix.os == 'ubuntu-20.04'
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        echo "$GPG_PRIVATE_KEY" | gpg --import
        echo "$GPG_PASSPHRASE" | gpg --batch --yes --passphrase-fd 0 --detach-sign dist/${{ matrix.asset_name }}

    - name: Upload Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/${{ matrix.asset_name }}
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: ${{ matrix.asset_content_type }}

    - name: Upload SHA256
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/${{ matrix.asset_name }}.sha256
        asset_name: ${{ matrix.asset_name }}.sha256
        asset_content_type: text/plain

    # Upload GPG signature for Linux binary
    - name: Upload Linux Signature
      if: matrix.os == 'ubuntu-20.04'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/${{ matrix.asset_name }}.sig
        asset_name: ${{ matrix.asset_name }}.sig
        asset_content_type: application/octet-stream

### Security Notes
- Our executable is signed with a digital signature for security
- If Windows SmartScreen shows a warning, click "More Info" then "Run Anyway"
- You can verify our signature by right-clicking the .exe → Properties → Digital Signatures
- The source code is available in this repository for transparency 